Feature/logic
yaairfernando/restaurant_page pull request #1
Opened 2020-04-14 15:54 UTC by YairFernando67

In this project, I implemented a restaurant home page using webpack and js modules.

2020-04-14 20:01 UTC, MauricioRobayo requested changes
This is some good looking code. Nice Webpack config. The page is looking great. Really good work, congratulations!

Remember that you are not supposed to modify linters config files, so one request:

* [ ] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))

Status: __Request chanages__:

2020-04-14 20:01 UTC, MauricioRobayo commented on .eslintrc.json
> +    "import/extensions": "off"
Please do not modify linters config.

2020-04-14 20:01 UTC, MauricioRobayo commented on src/contact.js
> +import '../styles/styles.css';
OPTIONAL: Why not import styles on index.js instead of importing it on every other page? :thinking:

2020-04-14 20:01 UTC, MauricioRobayo commented on src/contact.js
> +export default contact;
Nice done using IIFE and the revealing module pattern.

OPTIONAL: Since you are using Webpack to modularize and bundle your code, you could simplify this and let Webpack take care of the modules/scope:

```js
const info = () => { ...
};

const contactPage = () => { ...
};

export default { contactPage };
```

> Each module is a piece of code that is executed once it is loaded.
In that code, there may be declarations (variable declarations, function declarations, etc.).
**By default, these declarations stay local to the module.**
You can mark some of them as exports, then other modules can import them.

https://exploringjs.com/es6/ch_modules.html#_browsers-scripts-versus-modules

2020-04-14 20:01 UTC, MauricioRobayo commented on src/homepage.js
> +    tabTwo.appendChild(linkTwo);
OPTIONAL: Each line is duplicated :thinking: , and what if we want to add a third tab... maybe we could refactor this into a function, have some kind of data structure to store the changing parts, and map through it, that will make your code easier to maintain and you could easily add more tabs. Something like this, for example:

```js
const createTab = ({ id, textContent }) => {
  const tab = document.createElement('div');
  tab.classList.add(id);
  tab.id = id;
  const link = document.createElement('a');
  link.href = '#';
  link.textContent = textContent;
  tab.append(link);
  return tab;
};

const tabs = () => {
  const tabsContianer = document.createElement('div');
  tabsContianer.classList.add('tabs-container');
  const tabs = [
    { id: 'tab-one', textContent: 'Menu' },
    { id: 'tab-two', textContent: 'Contact Us' },
  ];
  tabsContianer.append(...tabs.map(createTab));
  return tabsContianer;
};
```

Again, since you are using modules, top-level variables are local to the module, so you could avoid the IIFE with the revealing module pattern.

2020-04-14 20:02 UTC, MauricioRobayo commented on package.json
> +    "server": "npm run clean && webpack && wait-on dist/index.html && browser-sync dist/ --watch",
OPTIONAL: You could also try [webpack-dev-server](https://github.com/webpack/webpack-dev-server)

2020-04-15 06:26 UTC, Oghenebrume50 approved these changes
### STATUS: CHANGES REQUIRED 

Hi @YairFernando67  good job on making changes as required by the previous TSE, this is an awesome project implemented by you, your code looks really nice :clap:  please merge and move on, **this is approved** :+1: 

**RAPHAEL NORIODE** :world_map:

2020-04-15 09:59 UTC, merged